### ISSUE TITLE
Thanks for this project! Greeting from mutliarch project

### ISSUE THREAD

**Issue by junaruga** [umarcor/qus#2]
Hi the project maintainer!
Thank your for developing this great inspirational project!
The implemented features and CI pipeline are amazing!

I am Jun Aruga. I recently became a member of "multiarch" project.
I just want to share you that as I was inspired from this project, I sent PR to "multiarch/qemu-user-static.
https://github.com/multiarch/qemu-user-static/pull/75

Kind regards,
Jun

**Comment by umarcor** [comment]
Hi @junaruga! Thanks a lot for your kind words. As a matter of fact, multiarch/qemu-user-static was the inspiration for this project, as you can see in https://github.com/dbhi/qus/blob/master/register.sh#L3.

> The implemented features and CI pipeline are amazing!

I hope to have the additional features in `qemu-binfmt-conf.sh` upstreamed at some point, so we can all benefit from them. Regarding the CI pipeline, I feel that the tests table is exhaustive but hard to understand for new users. Please, feel free to suggest any enhancement.

> I just want to share you that as I was inspired from this project, I sent PR to "multiarch/qemu-user-static. multiarch/qemu-user-static#75

I will have a look!

---

In the latest update to docker-for-win, QEMU 4.0.0 was included (for ARM binaries): https://docs.docker.com/docker-for-windows/release-notes/. I have not tested it yet, but it seems that some of the features provided by this project and/or by multiarch/qemu-user-static might not be required anymore. However, I don't know how/if it applies to GNU/Linux and/or macOS hosts; and/or to other architectures.

---

I'm closing this issue, but feel free to continue the discussion.

**Comment by jrcichra** [comment]
I also wanted to say thank you for this project. This project combined with docker buildx lets me build containers for various architectures in my CI pipelines. I also use this project to emulate x86 containers on raspberry pi's (for example, the steam linux client), for a raspberry pi lan cache solution.

Keep up the good work!

**Comment by umarcor** [comment]
Thanks @jrcichra! I'd love to have a look at some example where you are using this project along with buildx!

**Comment by jrcichra** [comment]
> Thanks @jrcichra! I'd love to have a look at some example where you are using this project along with buildx!

Sure! I nearly use it in every one of my repos: 
+ https://github.com/jrcichra/lancache-rpi/
+ https://github.com/jrcichra/rejson-buildx
+ https://github.com/jrcichra/karmen
+ https://github.com/jrcichra/smartcar

Directly, here's my CI bash script: https://github.com/jrcichra/karmen/blob/master/ci.sh
